pipeline {

    agent any

    environment {
        DOCKERHUB = credentials('dockerhub')
        SONAR = credentials('sonar-token')

        AWS_ACCESS_KEY = credentials('aws-access-key')
        AWS_SECRET_KEY = credentials('aws-secret-key')
        AWS_REGION_NAME = credentials('aws-region-name')
        AWS_BUCKET_NAME = credentials('aws-bucket-name')

        IMAGE = "black0list/cargosync:latest"
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo "📥 Pulling code from GitHub..."
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('xChain32') {
                    echo "🧪 Running Maven tests..."
                    sh """
                        mvn -version
                        mvn clean verify
                    """
                }
            }
            post {
                always {
                    dir('xChain32') {
                        echo "📦 Publishing test reports..."
                        junit '**/target/surefire-reports/*.xml'
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('xChain32') {
                    echo "🔍 Running SonarQube analysis..."
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            mvn sonar:sonar \
                              -Dsonar.projectKey=CargoSync \
                              -Dsonar.projectName='CargoSync' \
                              -Dsonar.host.url=http://38.242.220.11:9000 \
                              -Dsonar.login=${SONAR}
                        """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🐳 Building Docker image..."
                sh "docker build -t ${IMAGE} ."
            }
        }

        stage('Push to DockerHub') {
            steps {
                echo "📤 Pushing image to DockerHub..."
                sh """
                    echo "${DOCKERHUB_PSW}" | docker login \
                        --username ${DOCKERHUB_USR} --password-stdin
                    docker push ${IMAGE}
                """
            }
        }
    }

    post {
        success {
            echo "🚀 Pipeline completed successfully!"
        }
        failure {
            echo "❌ Pipeline failed."
        }
    }
}
