pipeline {

    agent any

    environment {
        DOCKERHUB = credentials('dockerhub')

        SONAR = credentials('sonar-token')

        // AWS Credentials from Jenkins
        AWS_ACCESS_KEY = credentials('aws-access-key')
        AWS_SECRET_KEY = credentials('aws-secret-key')
        AWS_REGION_NAME = credentials('aws-region-name')
        AWS_BUCKET_NAME = credentials('aws-bucket-name')

        // Docker image destination
        IMAGE = "black0list/cargosync:latest"

        SONAR_HOST_URL = "http://38.242.220.11:9000"
    }

    stages {

        stage('Checkout Code') {
            steps {
                echo "📥 Pulling code from GitHub..."
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                echo "🧪 Running Maven tests..."
                dir('xChain32') {
                    sh 'mvn clean verify'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo "🔍 Running SonarQube analysis..."

                withSonarQubeEnv('SonarQube') {
                    dir('xChain32') {

                        sh """
                            mvn clean verify sonar:sonar \
                                -Dsonar.projectKey=CargoSync \
                                -Dsonar.projectName='CargoSync' \
                                -Dsonar.host.url=${SONAR_HOST_URL} \
                                -Dsonar.token=${SONAR} \
                                -Dsonar.java.coveragePlugin=jacoco \
                                -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
                                -Dsonar.junit.reportPaths=target/surefire-reports \
                                -Dsonar.sources=src/main/java \
                                -Dsonar.tests=src/test/java \
                                -Dsonar.java.binaries=target/classes \
                                -Dsonar.java.test.binaries=target/test-classes \
                                -Dsonar.inclusions=src/main/java/**/service/**,src/main/java/**/controller/** \
                                -Dsonar.exclusions=src/main/java/**/entity/**,src/main/java/**/dto/**,src/main/java/**/mapper/**,src/main/java/**/config/**,src/main/java/**/exception/**,src/main/java/**/enums/**,src/main/java/**/repository/**,src/main/java/**/security/**,src/main/java/**/util/**,src/main/java/**/Application.java
                        """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🐳 Building Docker image..."
                dir('xChain32') {
                    sh "docker build -t ${IMAGE} ."
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                echo "📤 Pushing image to DockerHub..."
                sh """
                    echo "${DOCKERHUB_PSW}" | docker login \
                        --username ${DOCKERHUB_USR} --password-stdin
                    docker push ${IMAGE}
                """
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    cd /apps/cargosync
                    docker compose down
                    docker compose up -d --build
                '''
            }
        }
    }

    post {
        success {
            echo "🚀 Pipeline completed successfully!"
        }
        failure {
            echo "❌ Pipeline failed."
        }
    }

}
